version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/fran:/mnt:z
      - /mnt/usbdisk:/mnt2:z
    command: '-s "fran;/mnt;yes;no;yes;fran;fran;fran" -s "usbdisk;/mnt2;yes;no;no;fran;fran;fran" -u "fran;topo01"'
    #    -s "<name;/path>[;browse;readonly;guest;users;admins;writelist;comment]"


networks:
  default:
