---
version: "3"
services:

  reverse-proxy:
    #image: traefik
    image: traefik:v1.7
    container_name: traefik
    ports:
      - "80:80" # The HTTP port
      - "443:443" # The HTTPS port
      - "8080:8080" # The web UI
    networks:
      - backend
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:traefik.home.local"
      - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./conf/traefik.toml:/traefik.toml # Traefik configuration file
    restart: unless-stopped

networks:
  backend:  
    external: true
